version: "3.9"

services:
  api:
    build: ./app/api
    container_name: api
    ports:
      - "3000:3000"

  web:
    build: ./app/web
    container_name: web
    ports:
      - "80:80"
    environment:
      BASIC_AUTH_USER: user
      BASIC_AUTH_PASS: admin123
    depends_on:
      - api

