AWSTemplateFormatVersion: "2010-09-09"
Description: Sparkrock Test Infrastructure - EC2 + S3 + CloudWatch

Parameters:
  KeyName:
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  SparkrockSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH, HTTP, HTTPS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Environment
          Value: Staging
        - Key: Name
          Value: Sparkrock-Staging-SG

  SparkrockRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: "/"
      Tags:
        - Key: Environment
          Value: Staging
        - Key: Name
          Value: Sparkrock-Staging-Role

  SparkrockInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SparkrockRole
  SparkrockInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref SparkrockSecurityGroup
      IamInstanceProfile: !Ref SparkrockInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras enable docker
          yum install -y docker git
          service docker start
          usermod -aG docker ec2-user
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          echo "Docker & docker-compose installed"
      Tags:
        - Key: Environment
          Value: Staging
        - Key: Name
          Value: Sparkrock-Staging-EC2

  SparkrockEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref SparkrockInstance
      Tags:
        - Key: Environment
          Value: Staging
        - Key: Name
          Value: Sparkrock-Staging-EIP

  SparkrockBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sparkrock-logs-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Staging
        - Key: Name
          Value: Sparkrock-Staging-Logs

  SparkrockCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "CPU utilization > 70%"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: InstanceId
          Value: !Ref SparkrockInstance
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: []  # can hook SNS here
      Tags:
        - Key: Environment
          Value: Staging
        - Key: Name
          Value: Sparkrock-Staging-CPUAlarm

Outputs:
  InstanceId:
    Description: EC2 Instance Id
    Value: !Ref SparkrockInstance

  ElasticIP:
    Description: Public Elastic IP of the instance
    Value: !Ref SparkrockEIP

  S3BucketName:
    Description: Bucket name for logs
    Value: !Ref SparkrockBucket

  EnvironmentTag:
    Description: Environment tag applied to resources
    Value: Staging

  InstanceName:
    Description: Name tag for the EC2 instance
    Value: Sparkrock-Staging-EC2

  BucketNameTag:
    Description: Name tag for the S3 bucket
    Value: Sparkrock-Staging-Logs

