name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push API
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t tukilla/node-api:latest ./app/api --push

      - name: Build & push Web
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t tukilla/web-frontend:latest ./app/web --push

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.62.125.181
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            docker compose down
            docker compose pull
            docker compose up -d

